services:
  spring-back-end-1:
#    container_name: "spring-back-end-1"
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: springbackend.local
    depends_on:
      - mysql-container
      - rabbitmq-container

  mysql-container:
    image: mysql:8.3.0
    container_name: 'mysql-container'
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: employee_management_system
      MYSQL_ROOT_PASSWORD: root

  rabbitmq-container:
    image: rabbitmq:3.10.5-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
#    networks:
#      - rabbitmq_network

  loadbalancer:
    image: nginx:latest
    container_name: 'loadbalancer'
    volumes:
      - "./confd:/etc/nginx/conf.d"
    ports:
      - 80:80
    environment:
      DEFAULT_HOST: springbackend.local
    depends_on:
      - spring-back-end-1

  kafka:
    image: wurstmeister/kafka
    container_name: 'kafka'
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: 'zookeeper'
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - ~/.docker-conf/zookeeper/data/:/var/lib/zookeeper/data
      - ~/.docker-conf/zookeeper/log/:/var/lib/zookeeper/log
volumes:
  dbdata:

networks:
  rabbitmq_network:
    driver: bridge